spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: K3zR9Rmju2cMWES3dcORA9lXlRaQWmQr
    url: jdbc:postgresql://satao.db.elephantsql.com:5432/xwnntagj
    username: xwnntagj
